# Generated by Django 4.2.30 on 2026-09-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
